- name: install packages
  yum: 
    name: ['@^Virtualization Host', 'genisoimage', 'sqlite', 'keepalived', 'jq', 'vconfig', 'git', 'NetworkManager']
    state: present
  tags: [be_pkg]

- name: creates cloudland directory
  file:
    path: /opt/cloudland
    state: directory
  tags: [sync]

- name: synchronize cloudland
  synchronize:
    src: /opt/cloudland
    dest: /opt
    rsync_opts: "--exclude=cache,--exclude=log"
  tags: [sync]

- name: copy sci binaries
  copy: 
    src: /opt/sci
    dest: /opt
    mode: preserve
  tags: [sci]

- name: copy service file
  copy: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: preserve
  with_items:
    - {src: 'cloudlet.service', dest: '/lib/systemd/system', owner: 'root'}
    - {src: 'scid.service', dest: '/lib/systemd/system', owner: 'root'}
  tags: [be_srv]

- name: create cloudlet environment file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
  with_items:
    - {src: 'cloudlet.j2', dest: '/etc/sysconfig/cloudlet', owner: 'root'}
    - {src: 'cloudrc.local.j2', dest: '/opt/cloudland/scripts/cloudrc.local', owner: 'centos'}
  tags: [be_srv]
 
- name: start cloudlet services
  systemd: 
    name: "{{ item }}"
    enabled: yes
    daemon_reload: yes
    state: restarted
  with_items:
    - 'libvirtd'
    - 'NetworkManager'
    - 'scid'
    - 'cloudlet'
  tags: [be_srv]
